### ISSUE TITLE
convert_convai_lm_data.py has test inp file hardcoded

### ISSUE THREAD

**Issue by ghadiaravi13** [prakharguptaz/EDGE-exemplars#2]
The input file inside the prepare_lm_data function is hardcoded to test_inp_file, and so it always preprocesses test inp file inspite of specifying paths for train/valid input files. Was it intended, so as to pass each file seperately, one after another, under test_inp_file arg ?

**Comment by prakharguptaz** [comment]
Hi, yes, that part of the code is hardcoded and I forgot to change it. the inp_file variable should have been passed as an input to the prepare_lm_data function. You can change the input file based on split of the dataset that needs to be transformed and later merge the outputs of multiple splits into a single json file.

**Comment by ghadiaravi13** [comment]
Got it, thanks!
